---
title: "PackageIntroduction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{PackageIntroduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r message=F, warning=F}
library(dataCleaner)
library(printr)
library(dplyr)
```

```{r}
tibble::tibble(
  date = c("20190101", "20190305", "20201012"),
  numeric_val = c(1, NA, 5),
  char_val = c("", "val ", "-")
) -> sample_table

sample_table
```

```{r}
sample_table %>% 
  clean_frame 
```

```{r}
sample_table %>% 
  fill_na(where(is.numeric))
```
## Pivot summary

Transpose a tibble of summary statistics in tidy format. 

Can transpose 1 row numerical summaries by default.

```{r}
iris %>% 
  summarize(across(where(is.numeric), mean), .groups = "drop") %>% 
  pivot_summary()
```

A grouped summary can be transposed by providing the name of the group column.

```{r}
iris %>% 
  group_by(Species) %>% 
  summarize(across(where(is.numeric), mean), .groups = "drop") %>% 
  pivot_summary(Species)
```
Supports transposing numerical summaries with multiple groups using tidyselect. 

```{r}

iris %>%
  mutate(Species1 = sample(Species)) %>%
  group_by(Species, Species1) %>%
  summarize(across(where(is.numeric), mean), .groups = "drop") -> multigroup_summary
 
multigroup_summary
```
Group names are concatenated and pivoted.

```{r}
multigroup_summary %>% 
   pivot_summary(matches("Spec")) 
```

